### ISSUE TITLE
Possible typo 

### ISSUE THREAD

**Issue by omergra** [marco-rudolph/differnet#8] opened 2020-11-05 16:25 UTC
Hi, 
In train.py, line 89, you have  the code:
is_anomaly = np.array([0 if l == 0 else 1 for l in test_labels])
The thing is, that it seems that non-defective (or "good") data gets the label 1 in your code (your first class index in utils.py line 66:      class_idx = 1)

Shouldn't the correct code be: [0 if l == 1 else 1 for l in test_labels]?

Thanks,
Omer

**Comment by marco-rudolph** [comment] 2020-11-10 11:25
Hi,

for me it works as it should. See [this](https://github.com/marco-rudolph/differnet/blob/a484c6aebf8c82c48380770dfc34397182775e4a/utils.py#L68]) line and the following - the 'good' class is assigned to class 0. I just tested it another time and could not reproduce your issue. Can you?

Best regards,
Marco

**Closed as completed** 2021-01-07 17:05 UTC
